first-join:
  min-height: 0.85
  max-height: 1.15
potion:
  min-height: 0.5
  max-height: 1.3
  craft:
    shape:
      - "   "
      - " N "
      - " B "
    ingredients:
      N : NETHERITE_INGOT
      B : GLASS_BOTTLE
  name: "<!italic><gradient:#00C0DB:#1CBC95>Эликсир Роста</gradient></reset>"
  lore:
    - "<!italic><gradient:#00C0DB:#1CBC95>Размер на выбор</gradient>"
    - "<!italic><gradient:#00C0DB:#1CBC95>(Но выбирает зелье)</gradient>"
